### ISSUE TITLE
Add record updating functionality

### ISSUE THREAD

**Issue by dionkapf** [Rivine255/crime_stopper1.0#10]
Admins should be able to update the records saved to the database.

### Functions
- [ ] Viewing reports
Admin should be able to view each record as they appear on the database.
- [ ] Editing reports
Admin should be able to retrieve a report in a form which will allow them to edit the information appropriately. Admin should also be able to save the changes or discard them.
- [ ] Deleting reports
Admin should be able to delete reports as necessary from the database.
- [ ] Adding report
Admin should be able to add a report and save it on to the database similarly to how ordinary users do.

This issue is due on **Monday, 27 July 2020**

**Comment by Kefa12** [comment]
Finish work

**Comment by Kefa12** [comment]
Finish
