### ISSUE TITLE
Add admin updating functionality

### ISSUE THREAD

**Issue by dionkapf** [Rivine255/crime_stopper1.0#11]
Admins should be able to update admins in the database.

Admins should be able to update the records saved to the database.

### Functions
- [x] Adding admins
Admin should be able to add admin users and save their details on to the database.
- [x] Viewing admins
Admin should be able to view each admin as they appear on the database.
- [x] Editing admins
Admin should be able to edit the admin user's information appropriately. Admin should also be able to save the changes or discard them.
- [ ] Deleting admins
Admin should be able to delete admin users as necessary from the database.

This issue is due on **Monday, 27 July 2020**

**Comment by Kefa12** [comment]
Finished
